### ISSUE TITLE
Problems with tcp connection

### ISSUE THREAD

**Issue by niccarey** [smcgill3/zeromq-matlab#4]
Hi!
am trying the test_zmq script on Ubuntu 14.04, R2013b. Installation seems fine, connecting with icp works ok. However I can't get the tcp connection to work (using localhost/127.0.0.1 on port 4000).

Setting up the subscribe/publish tcp channels returns no errors, but polling returns no tcp channel to the idx. Doesn't seem to matter whether I have echotcpip toggled on or not. Should I be able to do an echo test on localhost, or should I try an actual remote machine? Mostly I just want to make sure I can use matlab to send/receive remotely via zmq, before trying to set up a connection to our hardware API.

Sorry if this is a silly question, I haven't done anything with zmq before and am trying to figure things out as I go!

**Comment by smcgill3** [comment]
I have it working for me on 2015a. The caveat is that poll needs to be run at least once before sending (at least for localhost). The test script has been updated. The polling works on the first shot for me if listening for messages from another computer. I'm not sure what the issue is, but I may look into it in the future. Thanks for the note.

**Comment by niccarey** [comment]
Thanks! added an initial poll and worked straight away. Awesome.
